# Generated by Django 5.1.5 on 2025-02-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_appointment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opdqueue',
            options={'ordering': ['priority', 'created_at']},
        ),
        migrations.AddField(
            model_name='opdqueue',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opdqueue',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_consultation', 'In Consultation'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
