# Generated by Django 5.1.5 on 2025-02-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_appointment_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time', 'doctor')},
        ),
    ]
