# Generated by Django 5.1.5 on 2025-02-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_medicine_prescription_medicines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_images'),
        ),
    ]
